from pathlib import Path

import pandas as pd
from IPython.display import display


TOP100_CSV = Path(
    "/kaggle/working/sensex_individual_decay_scaling_top100.csv"
)

RANKED_PARQUET = Path(
    "/kaggle/working/sensex_individual_decay_scaling_ranked.parquet"
)

OUTPUT_CSV = Path(
    "/kaggle/working/sensex_individual_decay_scaling_structured_top20.csv"
)


OUTPUT_COLUMNS = [
    "rank",
    "monitor_start",
    "monitor_premium",
    "individual_decay_trigger_pct",
    "lot1_entry_premium",
    "lot1_profit_to_lot2_pct",
    "lot2_entry_premium",
    "lot2_profit_to_lot3_pct",
    "lot3_entry_premium",
    "campaign_sl_rs",
    "campaign_sl_reversal",
    "exit_time",
    "status",
    "campaign_count",
    "lot2_activation_count",
    "lot3_activation_count",
    "campaign_sl_count",
    "reversal_count",
    "max_campaign_loss",
    "win_rate",
    "max_consecutive_losses",
    "entry_robust_side",
    "net_pnl",
    "pnl_2025",
    "pnl_2026",
    "mtm_dd_2025",
    "mtm_dd_2026",
]


def load_ranked_data():
    if TOP100_CSV.exists() and TOP100_CSV.stat().st_size > 0:
        data = pd.read_csv(TOP100_CSV)
        source = TOP100_CSV
    elif RANKED_PARQUET.exists():
        data = pd.read_parquet(RANKED_PARQUET)
        source = RANKED_PARQUET
    else:
        raise FileNotFoundError(
            "Neither the Top 100 CSV nor ranked Parquet was found. "
            "Run the ranking script first."
        )

    if data.empty:
        raise ValueError("The ranked input contains zero rows.")

    print("Reading ranked input:", source)
    return data


def main():
    data = load_ranked_data()

    # Preserve the ranking order generated by the ranking script.
    if "rank" in data.columns:
        data = data.sort_values("rank", kind="stable")

    data["entry_robust_side"] = data[
        "entry_robust_side"
    ].replace(
        {
            "prior_side": "before",
            "after_side": "after",
            "both_sides": "both",
        }
    )

    # Add only requested output columns if a source column is absent.
    for column in OUTPUT_COLUMNS:
        if column not in data.columns:
            data[column] = pd.NA

    structured_top20 = data[OUTPUT_COLUMNS].head(20).copy()
    structured_top20.to_csv(OUTPUT_CSV, index=False)

    print("Structured output:", OUTPUT_CSV)
    print("Rows written:", len(structured_top20))
    print("Columns written:")
    print(list(structured_top20.columns))
    print()
    display(structured_top20)


if __name__ == "__main__":
    main()
